apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: spinnaker
  name: prometheus-redis
  labels:
    app: prometheus-redis-exporter
    release: prometheus-operator
spec:
  endpoints:
  - honorLabels: true
    targetPort:
  selector:
    matchLabels:
      app: prometheus-redis-exporter
      release: my-redis-exporter
    namespaceSelector:
      any: true

